### ISSUE TITLE
Tool does not process multi-partitioned UBV files

### ISSUE THREAD

**Issue by touche112** [petergeneric/unifi-protect-remux#1]
Creating official issue for linking to BountySource.  Per documentation:

"Currently this tool only works with single partition files. In the future it will be expanded to work with multiple partitions, by creating multiple .mp4 files."

This issue is to correct this and allow processing on multi-partitioned UBV files.

**Comment by touche112** [comment]
https://www.bountysource.com/issues/92192494-tool-does-not-process-multi-partitioned-ubv-files

**Comment by petergeneric** [comment]
Thanks, this has actually been quite helpful to motivate me to do some work on this again - I've added support for multi-partition .ubv files (also refactored the parser and added some unit tests to make things a bit more structured) in 01566459b1711f701a5b0d7abb0c26ec2a14a21b

I've tested it on a timelapse .ubv file from my system. When encountering a multi-partition file it writes several output .h264 streams - these can either be kept separate, concatenated with a simple cat execution or with FFmpeg as part of the remux to an MP4 container.
