### ISSUE TITLE
Audio Extraction not working?

### ISSUE THREAD

**Issue by majerus1223** [petergeneric/unifi-protect-remux#16]
I have tried a few ways, but cannot seem to get the audio extraction bit to work. If you would like I can send you a link to a ubv file. 

 ```  remux F09FC213A880_2_rotating_1630289032914.ubv --with-audio=true```

   ```remux F09FC213A880_2_rotating_1630289032914.ubv -with-audio```

Both produce video, however there is also an error that is thrown 'Error Waiting for ubv: exit status 2'

```2021/10/31 10:39:51 Analysing  --with-audio=true```
``` 2021/10/31 10:39:51 Error waiting for ubv: exit status 2```

I am running this from the CKG2+.

Thanks!

BTW this tool is pretty awesome even if I cannot get the audio to work!

**Comment by petergeneric** [comment]
That error sounds like there's something wrong with that .ubv file... a link to the .ubv would certainly help but I can also send you a diagnostic command to run instead if you'd prefer? peter at peterphi dot com if you'd like to e-mail a link privately

**Comment by petergeneric** [comment]
Hi,

I've not got an e-mail about this, nor an update on the ticket - did you get the issue sorted?

**Comment by majerus1223** [comment]
Hey, sorry missed your message. If you have a diagnostic tool command that would be great!

**Comment by JRichter1234** [comment]
I'm having the same issue as majerus1223...

- Video is from a CKG2+ hdd, mounted in an external drive USB adapter
- I used a combination of 'unifi-protect-remux' and ‘TokugawaHeavyIndustries/ubv-remux-docker’ so I could get the ‘ubnt_ubvinfo’ file
![Remux Audio Issue](https://user-images.githubusercontent.com/93527125/140165840-64bfca7c-acc0-428a-8a6a-366b68f8ff1b.jpg)

Could I get the diagnostic tool command too please! Thx!

**Comment by petergeneric** [comment]
@majerus1223 don't know why I missed that, but it looks like that's your issue also. Can you try that and let me know if it resolves it? "*.ubv" should be the last argument

**Comment by JRichter1234** [comment]
> Aha! That looks to be caused by a bug in the Go commandline parser treating your with-audio flag as a file input - can you change it to remux --with-audio=true *.ubv" instead?

She works beauty!
Thanks so much for your help Peter!
