### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Spectatorny** [petergeneric/unifi-protect-remux#17]
Hi Petergeneric, 

I have extracted video files from the UCK-G2-Plus device and copied them to my Kali machine.  When I run the program I get the following error "ubnt_ubvinfo not on PATH, nor in any default search locations!".  Can you please tell me if I'm missing any files from the UCK-G2-Plus device that I need to retrieve. Is there a work around this error. 

Cheers

**Comment by petergeneric** [comment]
Yes, you'll need to follow the Quick Start for x86 Linux at https://github.com/petergeneric/unifi-protect-remux and retrieve the ubnt_ubvinfo tool
