### ISSUE TITLE
Exit status 5?

### ISSUE THREAD

**Issue by WillemvdKletersteeg** [petergeneric/unifi-protect-remux#19]
Hi! I'm trying to remux a single ubv file as a test, but somehow it runs into some timeout waiting for input and then exits with status 5. This is the output:
`2021/12/30 14:53:52 Analysing  0418D650FA9D_2_timelapse_1610037463242.ubv
2021/12/30 14:53:52 First Frame: 2021-01-07 17:05:32.802 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2020-12-15 10:29:40.066 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-13 06:06:18.658 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-13 15:49:17.059 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-14 03:23:38.583 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-21 10:30:37.033 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-22 03:05:35.719 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-01-31 03:04:14.298 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-02-15 17:46:04.833 +0100 CET
2021/12/30 14:53:52 First Frame: 2021-02-15 17:53:30.386 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-02-23 13:27:51.405 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-03-01 16:56:12.11 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-04-22 03:04:23.448 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-05-17 17:06:42.817 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-05-20 03:19:23.494 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-06-11 11:03:42.502 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-07-06 10:07:47.207 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-10-21 03:27:50.765 +0200 CEST
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:53:52 First Frame: 2021-11-02 03:09:31.397 +0100 CET
2021/12/30 14:53:52 Video Rate Probe: WARNING probed rate was 0 fps. Assuming timelapse file and using 1fps
2021/12/30 14:54:49 Error waiting for ubv: exit status 5
`
I'm trying to figure out whats happening by analysing the code. It seems to be happening in the runUbvInfo() function (ubv/ubvinfo.go) but I honestly have no clue why or where to start figuring this out further...

**Comment by petergeneric** [comment]
Hi,

This tool isn't really designed to be used on timelapse files, since they're a low-res low-framerate copy of the original files. Are you able to extract the footage from the master files instead?

The "exit status 5", btw, means that the ubiquiti tool failed when running against the file, which suggests it might be corrupt (or might be on an unusual filesystem that it appears to have difficulty with)

**Comment by petergeneric** [comment]
Closed due to inactivity
