### ISSUE TITLE
Error parsing track number!strconv.Atoi: parsing "--file=": invalid syntax

### ISSUE THREAD

**Issue by VolkanGit** [petergeneric/unifi-protect-remux#21]
I have the same issue

user@ubuntu:~$ ./remux *.ubv
2022/01/22 02:26:49 Analysing B4FBE47EFC73_0_rotating_1559064862165.ubv
2022/01/22 02:26:49 Error parsing track number!strconv.Atoi: parsing "--file=": invalid syntax

user@ubuntu:~$ /usr/bin/ubnt_ubvinfo -P -f ./B4FBE47EFC73_0_rotating_1559064862165.ubv > output.txt
At least one file path is mandatory

output.txt:
usage: /usr/bin/arm-ubnt_ubvinfo

MANDATORY OPTIONS:
-f, --file= The path of the ubv file to be analyzed.
Can be specified multiple times.

OPTIONALS:
-h, --help Prints this help and exits.
-r, --clock-rate= When listing time components, use the specified
clock rate. If not specified, the original clock
rate will be used. For example, 1000 means that
all time components will be expressed in
milliseconds
-z, --zero-base Rebase all timestamps to 0. Ignored if the clock
rate is not specified
-t, --tid= The TID of the track to be dumped. If not
specified, all tracks will be dumped.
-p, --partitions List partitions only
-P, --partitions-boundaries Show partitions boundaries in the output
-k, --keyframes List key frames only
-H, --human-readable-wc Print the wall clock in human readable form
-s, --sync-nodes Show synchronization nodes in the output
^[[01;33m:140 Shutting down the logger leaving you in the dark. Bye bye... :(^[[0m
^[[0m
~
~
~

**Comment by VolkanGit** [comment]
I thought of testing if I can get it to run
qemu-aarch64 -L /usr/aarch64-linux-gnu /usr/bin/arm-ubnt_ubvinfo -f *.ubv >output.txt

output start with
Type   TID  KF           OFFSET     SIZE          DTS   CTS              WC     CR
   V     7   1               84   156309   1966664441     0 140315837058011  90000       0
   A  1000   1           156416      371    240916918     0  17188690040130  11025      48
   V     7   0           156808     1670   1966670442     0 140315837064012  90000      19
   V     7   0           158500     3269   1966676441     0 140315837070011  90000      66
   A  1000   1           161792      372    240917942     0  17188690041154  11025       8

So it's able to run, but remux is not able to use it somehow.

**Comment by petergeneric** [comment]
I wonder - are there spaces in the path or the ubv filename? Just trying to think of reasons you'd be getting that error -- the track number parsing "--file=" suggests that the ubnt_ubvinfo script is outputting the help text rather than the expected data you're seeing with "Type TID" etc.

Can you try editing the ubnt_ubvinfo shell script I provided in the instructions and replacing:
```
$*
```

with the following (including quotes)
```
"$@"
```

And see if that changes anything?

**Comment by VolkanGit** [comment]
ok , I checked the and the $* was nog included. I thought it was strange, so I tested making the file again

user@ubuntu:~$ sudo tee test <<EOF
> #!/bin/sh
> export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
> exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo $*
> EOF
#!/bin/sh
export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo
user@ubuntu:~$ 

tee command doesn't write the $*

Thank you!

**Comment by petergeneric** [comment]
Ahh of course! Thanks, I'll fix that in the instructions

**Comment by bitboy00** [comment]
Fortunately, someone else had the problem before me.
It didn't work for me either with the current instructions. I used with VI and inserted the "$*". Now it works.

THANKS for the tool!
