### ISSUE TITLE
Error waiting for ubv: exit status 1

### ISSUE THREAD

**Issue by arretx** [petergeneric/unifi-protect-remux#22]
I have successfully remuxed ubv filed directly on my Dream Machine Pro, but the problem I have is that I'm running out of space so I need to copy those files to my Ubuntu 20.04 machine and run it in Linux.  

I've copied the ubnt_ubvinfo file from my UDMPro and have placed it in /usr/bin which is in my $PATH, and I have extracted the appropriate x86 remux as well as installed ffmpeg in Ubuntu 20.04 LTS.

When I attempt to run "remux *.ubv" I get the "Analysing" line, then immediately get the "Error waiting for ubv: exit status 1" message.  

Any ideas?

**Comment by petergeneric** [comment]
Have you tried running ubnt_ubvinfo on your system? I think that's the error you'd get if you tried to use the ARM binary directly on an x86 machine. There are instructions in the README for how to use qemu to run the ARM binary on x86, see https://github.com/petergeneric/unifi-protect-remux#dependencies-ubnt_ubvinfo-from-cloudkey=

**Comment by arretx** [comment]
Got it.  I had done that but somehow got wires crossed.  

I'm running this in Ubuntu which is running as a VM on my Unraid NAS.  One of my Unraid NAS shares is mounted in the Ubuntu VM.

I'm currently running a recursive SCP command directly on the UDMPro to copy all UBV files from the /video folder on the UDMPro to the NAS share through the Ubuntu mounted folder, then I'm using a command prompt on the Ubuntu box to run the `remux` command on the NAS share that has all of the UBV files in it.

All of the work is being done by the same computer since everything (except the UDMPro) is running on that Unraid box, but it seems like a convoluted way to go about it.

Could I run `remux` directly on the Unraid box using the unraid root command prompt, bypassing the Ubuntu machine completely?

**Comment by petergeneric** [comment]
I'm not familiar with unraid but since it's just linux ```remux``` should run just fine. As long as ```ubnt_ubvinfo``` runs on it you should be good. The README has instructions for Ubuntu, but only because that's what I run - if you find that you need to do anything different to get it running on unraid please let me know and I'll update the README (or go ahead and submit it as a PR)
