### ISSUE TITLE
Error waiting for ubv: exit status 1

### ISSUE THREAD

**Issue by love4speed** [petergeneric/unifi-protect-remux#24]
I am running remux on ubuntu 22.4
when I try to remux *.ubv I get analyzing  file_name_.ubv then get follwoing error:
"Error waiting for ubv: exit status 1"

Here is the actual command from terminal:
ubuntuadmin@ubuntu01:~/Downloads/FLOWER-VEG/02$ ls
68D79ACFC70E_0_rotating_1664725780179.ubv
68D79ACFCC9D_0_rotating_1664723821515.ubv
68D79AE2ADE7_0_rotating_1664718151200.ubv
68D79AE2ADEF_0_rotating_1664718037487.ubv
68D79AE3480E_0_rotating_1664724931215.ubv
68D79AE34998_0_rotating_1664721366237.ubv
68D79AE35193_0_rotating_1664722917599.ubv
ubuntuadmin@ubuntu01:~/Downloads/FLOWER-VEG/02$ remux *.ubv
2022/10/06 17:55:05 Analysing  68D79ACFC70E_0_rotating_1664725780179.ubv
2022/10/06 17:55:05 Error waiting for ubv: exit status 1

I should mention i followed these instructions: https://github.com/petergeneric/unifi-protect-remux#dependencies-ubnt_ubvinfo-from-cloudkey

What is the issue?

**Comment by love4speed** [comment]
> Are you using a shell script wrapper around ubnt_ubvinfo, or are you using the native x86 or ARM64 version? If so can you run `cat ubnt_ubvinfo` -- there was a bug in the readme (which I thought was fixed) for the qemu wrapper script.

I think I fixed my problem... I am running it now will post if any issues. Thank you for replying

**Comment by petergeneric** [comment]
Closing this issue, raise a new one if you have any trouble
