### ISSUE TITLE
where to find ubnt_ubvinfo on Dream Machine Pro

### ISSUE THREAD

**Issue by joloman2** [petergeneric/unifi-protect-remux#27]
hi i have a Dream Machine Pro and im trying to convert the files but can find the ubnt_ubvinfo file cous its not in /usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo

**Comment by petergeneric** [comment]
Try running the following instead to find it:
```
find / -name ubnt_ubvinfo
```

**Comment by joloman2** [comment]
works thanks found it
