### ISSUE TITLE
Remux : Command Not Found

### ISSUE THREAD

**Issue by LeeJSA** [petergeneric/unifi-protect-remux#28]
Running on Unifi OS - Cloud Key G2+ v2.1.11

Copied remux-arm64.tar.gz and ffmpeg-release-arm64-static.tar.xz into the /home directory on the box using WinSCP.

Extracted using the following commands

tar -xf remux-arm64.tar.gz && rm remux-arm64.tar.gz && chmod +x remux

xz -d ffmpeg-release-arm64-static.tar.xz && tar -xf ffmpeg-release-arm64-static.tar && mv ffmpeg*arm64-static/ffmpeg ./ && rm ffmpeg-release-arm64-static.tar.xz && chmod +x ffmpeg

Ran 

export PATH=$HOME:$PATH

Then navigated to where the UBV files are and tried to run remux <filename>.ubv and got the response...

-bash: remux: command not found

Also navigated to the /home directory and tried to run it again from there with the full file path to the UBV file and still received the same message.

HELP....what have I done wrong please?

Thanks

**Comment by petergeneric** [comment]
Try running the following to see if remux is definitely being picked up from your path:
```
which remux
```

Can you also try running ./remux from your home directory to see if that produces any useful error message?


Can you send the output of:
```
file $(which remux)
```

**Comment by LeeJSA** [comment]
Thanks for your reply Peter. Please see pic attached.
![remux](https://user-images.githubusercontent.com/120384290/207144498-37fd39a8-1e8c-4031-8794-65f4a9025888.png)

**Comment by petergeneric** [comment]
Ok, the output from `which` indicates that remux isn't in your path. Can you check to make sure it's definitely there?
If so, can you provide the output of:

```
stat remux
file remux
```

(What I'm wanting to check is that it's definitely the Linux ARM64 version and not the macOS ARM64 version you have)

**Comment by LeeJSA** [comment]
It didnt find remux until I changed into the home dir. Please see pic.
![remux2](https://user-images.githubusercontent.com/120384290/207145978-ee4db5df-6e14-4753-85a2-019e6f1c879c.png)

**Comment by LeeJSA** [comment]
YES! That was it! So simple too - I really need to learn more Linux! Really appreciate your help Peter. Now to download 4 full days worth of footage for the client!!
![remux3](https://user-images.githubusercontent.com/120384290/207148321-df3d1670-3d77-47c7-96d2-d9be8e1b0060.png)

**Comment by petergeneric** [comment]
Great! Enjoy :-)
