### ISSUE TITLE
Unable to run on X86 machine

### ISSUE THREAD

**Issue by TNwestpointtg** [petergeneric/unifi-protect-remux#29]
Hi, I followed the instructions for running on ubuntu 20.04 (albeit on 22.04),

When running I get this error:

2023/04/12 18:59:26 Analysing  E063DAAF925D_0_rotating_1677661887138.ubv
2023/04/12 18:59:26 Error waiting for ubv: exit status 1

I can't seem to work out what is going on? Any ideas? Thanks

**Comment by petergeneric** [comment]
Is this running on a native linux filesystem or on a WSL/WSL2 mount? If WSL, that seems to have caused problems in the past.

Otherwise - this indicates an error with the ubnt_ubvinfo tool, you can usually run it directly and see what error gets output, try:
```
ubnt_ubvinfo -f " E063DAAF925D_0_rotating_1677661887138.ubv" | head
```

(You may need to replace the command with a direct path to ubnt_ubvinfo if it's not already on your PATH)

**Comment by TNwestpointtg** [comment]
I should have mentioned - its running on the native root OS drive, it is a VM I've spun up or it

**Comment by petergeneric** [comment]
Ah, there's a space before the "E06D" in the filename, is that it?

**Comment by TNwestpointtg** [comment]
I tried it with and without, You example above had it, so I wasn't sure if it was right, same affect?

**Comment by petergeneric** [comment]
oh it should be without, sorry was typing on a phone! Try just issuing the following to make sure the file is definitely there and readable?
```
stat "E063DAAF925D_0_rotating_1677661887138.ubv"
```

If you can get ubnt_ubvinfo to run without error against the file then the remux app should run fine (it's just running ubnt_ubvinfo and then extracting positions from the output and writing them into atomic streams for ffmpeg to mux into an .mp4)

**Comment by TNwestpointtg** [comment]
Thanks - it runs on my cloudkey but not on the linux box, but I have 150GB of video I want to extract, my cloudkey doesn't have the storage without deleting old video, so I may just end up having to add a USB Hard drive to the cloudkey and running it from there with the output to the usb drive. Thanks for your support anyway :)
