### ISSUE TITLE
Question: Why sometimes the video is stored in low-res instead of the native 4K of the camera

### ISSUE THREAD

**Issue by ocalvo** [petergeneric/unifi-protect-remux#35]
**Describe the bug**
Not a bug but a question: Why sometimes the video is stored in low-res instead of the native 4K of the camera

**Command line arguments to reproduce**
N/A

**Output**
N/A

**ubnt_ubvinfo output**
N/A

**Your Hardware**
N/A

**Additional context**
N/A

**Comment by petergeneric** [comment]
You are probably looking at the low-res proxy files that are intended for scrubbing through the timeline, rather than the `*_0_rotating_*.ubv` files
