### ISSUE TITLE
Instructions for copying video files using scp

### ISSUE THREAD

**Issue by coltenkrauter** [petergeneric/unifi-protect-remux#36]
Hi there, it seems that this tool would be incredibly useful _after_ getting my hands on the video footage right from my UDM-PRO. Can you please provide documentation or instructions for using SCP to copy video footage from my UDM-PRO to my laptop or NAS?

Thanks a lot, neat tool.

**Comment by petergeneric** [comment]
Hi,

That's beyond the scope of this repo, but it's pretty straight-forward to enable SSH access (certainly on the Cloud Key G2) - you should find plenty of info online or on the ubiquiti community forums
