### ISSUE TITLE
Newb question here

### ISSUE THREAD

**Issue by Amward12** [petergeneric/unifi-protect-remux#41]
I followed you instruction for the x86 and I didn't run into any errors for the most part. I checked to insure that qemu is installed on the system I want to run this tool on and it is. I also verified that the script was actually made and written to my bin directory but when I try and run remux *.ubv it says "Command 'remux' not found". Is there a way to determine why it doesn't recognize it as a command? Or more importantly where is this command set? is it a bashrc entry I need to make? Also in this step here : 
Copy /usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo from your CloudKey to /usr/bin/arm-ubnt_ubvinfo on your x86 machine
I assume I am renaming the file i pulled from my Dream machine pro from "unbt_ubvinfo" to "arm-ubnt_ubvinfo". Apologies in advance, Im not a seasoned Linux veteran.

**Comment by petergeneric** [comment]
Hi,

I'm assuming the `remux` tool is also in your bin directory (which I'm assuming is one of the directories listed if you run `echo $PATH`) then it might be permissions. Try running `chmod +x /path/to/remux`.


If that still doesn't work, try this:

```
/path/to/remux --version
```

If *that* doesn't work, check that you have the right build of the tool:
```
file /path/to/remux
```

That should output something like `ELF 64-bit LSB executable, x86-64`, if it doesn't then you may have downloaded the arm version of `remux` by mistake.
