### ISSUE TITLE
Add support for timelapse ubvs

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [petergeneric/unifi-protect-remux#9]
At present, current tool cannot process timelapse ubv files, only rotating.

Relevant log output:

```
2021/01/13 03:57:40 Analysing  /remux/B4FBE49E9086_0_timelapse_1565048137805.ubv
2021/01/13 03:57:40 First Frame timestamp 2019-08-05 23:26:31.615 +0000 UTC
2021/01/13 03:57:40 Second Frame timestamp 2019-08-05 23:26:46.66 +0000 UTC
2021/01/13 03:57:40 First Frame timestamp 2019-08-09 10:23:17.664 +0000 UTC
2021/01/13 03:57:40 Second Frame timestamp 2019-08-09 10:23:32.65 +0000 UTC
2021/01/13 03:57:42

Analysis complete!
2021/01/13 03:57:42 First Partition:
2021/01/13 03:57:42     Tracks: 1
2021/01/13 03:57:42     Frames: 19901
2021/01/13 03:57:42     Start Timecode: 2019-08-05T23:26:31Z
2021/01/13 03:57:42

Extracting 2 partitions
2021/01/13 03:57:43
Writing MP4  /remux/B4FBE49E9086_0_timelapse_2019-08-05T23.26.31Z.mp4 ...
2021/01/13 03:57:43 Running:  [ffmpeg -i /remux/B4FBE49E9086_0_timelapse_2019-08-05T23.26.31Z.h264 -c copy -r 0 -y -loglevel warning /remux/B4FBE49E9086_0_timelapse_2019-08-05T23.26.31Z.mp4]
[h264 @ 0x6a85240] Stream #0: not enough frames to estimate rate; consider increasing probesize
Invalid framerate value: 0
2021/01/13 03:57:43 FFmpeg command failed! Error: exit status 1
```

**Comment by petergeneric** [comment]
The reason for this is that the framerate extraction code assumes an integer framerate of at least 1fps, whereas timelapses look to be around 1 frame per 15 seconds.

you can work around this for now using the --force-rate argument:
```remux --force-rate=1 sample.ubv```

I'm making a change to assume a framerate of 1fps if the framerate is guessed at 0 (it doesn't actually honour 1 per second, FFmpeg doesn't seem to want to use a very low framerate with a remux)

**Comment by petergeneric** [comment]
Please see release at: https://github.com/petergeneric/unifi-protect-remux/releases/tag/3.0.2

**Comment by petergeneric** [comment]
Hi,

Can you please test with https://github.com/petergeneric/unifi-protect-remux/releases/tag/v3.0.3 and let me know how it goes?
